apiVersion: v1
kind: Service
metadata:
  name: mler-app-service
  labels:
    app: mler-mler-app
spec:
  type: LoadBalancer  # Utilisez LoadBalancer pour exposer l'application sur Internet
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: mler-mler-app
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  labels:
    app: ollama
spec:
  type: ClusterIP  # ClusterIP est utilisé pour exposer le service au sein du cluster uniquement
  ports:
  - port: 11434
    targetPort: 11434
  selector:
    app: ollama
